#$ -S /bin/bash
#$ -l h_vmem=1.0G
#$ -l mem_free=1.0G
#$ -l virtual_free=1.0G
#$ -l h_rt=999:00:00
###$ -pe smp 4

set -eu

export PATH=${PATH}:/home/vicker/git_repos/crosslink/scripts
export PATH=${PATH}:/home/vicker/git_repos/crosslink/pag_poster

ERATE=$1
NMARKERS=$2
REP=$3

STATSFILE=stats/crosslink_only.csv
OUTDIR=crosslinkonly_data

NLGS=1
LGSIZE=${NMARKERS}
PROB_HK=0.333
PROB_LM=0.5
POPSIZE=200
MISSING=${ERATE}
ERROR=${ERATE}
MAPFUNC=1

FNAME=$(printf "test%s_%s_%s" ${ERATE} ${NMARKERS} ${REP})

#create map with randomly placed markers
create_map --out ${OUTDIR}/${FNAME}.map\
           --nmarkers ${NMARKERS}\
           --nlgs ${NLGS}\
           --lg_size ${LGSIZE}\
           --prob_hk ${PROB_HK}\
           --prob_lm ${PROB_LM}\
           --hideposn 1
           
#simulate genotyping data from the markers
sample_map --inp ${OUTDIR}/${FNAME}.map\
           --out ${OUTDIR}/${FNAME}.loc\
           --orig ${OUTDIR}/${FNAME}_orig.loc\
           --hide_hk_inheritance 1\
           --randomise_order 1\
           --nind ${POPSIZE}\
           --prob_missing ${MISSING}\
           --prob_error ${ERROR}\
           --map_func ${MAPFUNC}
           
           
#create file listing only marker names and cm pos in correct order 
tail -n +2 ${OUTDIR}/${FNAME}.map\
    | awk '{print $1, $5}'\
    > ${OUTDIR}/${FNAME}.map.order

#run cross link
START_SECS=$SECONDS
test_crosslink_small.sh ${OUTDIR}/${FNAME}.loc ${OUTDIR}
TOTAL_SECS=$(($SECONDS - $START_SECS))
SCORE=$(calc_spearmans.py\
            ${OUTDIR}/${FNAME}.map.order\
            ${OUTDIR}/${FNAME}.order)
echo ${ERATE} ${NMARKERS} ${REP} ${SCORE} ${TOTAL_SECS} >> stats/${FNAME}.csv
